###########################################################################
# List of languages							  #
# Each language is represented by a list of three elements. The first is  #
# the shorthand name of the language (this is the name which is used in   #
# all the structures, filenames and procedures. The second is the name of #
# the language (in the language itself) (this will be used in menus etc). #
# The last element is the character set that should be used for this      #
# language.                                                               #
###########################################################################
set languages { {sv Svenska iso8859-1}
		{en English ascii}
		{de Deutsch iso8859-1}
		{it Italiano iso8859-1}
		{fr Français iso8859-1}
		{sr Srpski iso8859-2}
		{pl Polski iso8859-2}
                {pt Português iso8859-1}}


# The following message is inserted at the top of every generated file
set message {#################################################################
# DO NOT EDIT!
#
# This file is automatically generated from files in the Text/ subdirectory
#
#  TkRat software and its included text is Copyright 1996-2004 by
#  Martin Forssen
#
#  The full text of the legal notices is contained in the file called
#  COPYRIGHT, included with this distribution.
#
}

# The following message is inserted at the end of every generated file
set trailer {#
# DO NOT EDIT!
# This file is automatically generated from files in the Text/ subdirectory
##############################################################################
}
